// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1922.TinManIX2.subsystems;

import org.usfirst.frc1922.TinManIX2.RobotMap;
import org.usfirst.frc1922.TinManIX2.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController rearLeftSC = RobotMap.driveTrainRearLeftSC;
    SpeedController rearRightSC = RobotMap.driveTrainRearRightSC;
    SpeedController frontLeftSC = RobotMap.driveTrainFrontLeftSC;
    SpeedController frontRightSC = RobotMap.driveTrainFrontRightSC;
    RobotDrive robotDrive41 = RobotMap.driveTrainRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    RobotDrive robotdrive = new RobotDrive(frontLeftSC, rearLeftSC, frontRightSC, rearRightSC);
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Drive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void takeJoystickInputs(Joystick left, Joystick right){
    		//Normally would be done through a general command but this works better for inverting motors
    		//Set inverted motor is borked through robot builder. (Negatives before "left.~" and "right.~" invert fyi)
    		rearLeftSC.set(-left.getY());
    		frontLeftSC.set(-left.getY());
    		rearRightSC.set(right.getY());
    		frontRightSC.set(right.getY());
    }
    
    public void stop(){
    	//Turning the motors' power off to stop the operation.
    	robotdrive.drive(0, 0);
    }
}

